import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/transaction_model.dart';
import '../models/category_model.dart';
import '../providers/transaction_provider.dart';
import '../providers/category_provider.dart';
import '../widgets/category_quick_selector.dart';
import '../utils/debt_utils.dart';
import 'package:finance_app/l10n/generated/app_localizations.dart';

class SplitPartState {
  final TextEditingController amountController;
  final TextEditingController noteController;
  String? categoryId;

  SplitPartState({
    required double initialAmount,
    this.categoryId,
    String initialNote = '',
  })  : amountController = TextEditingController(
            text: initialAmount > 0 ? initialAmount.toStringAsFixed(2) : ''),
        noteController = TextEditingController(text: initialNote);

  void dispose() {
    amountController.dispose();
    noteController.dispose();
  }
}

class SplitTransactionScreen extends ConsumerStatefulWidget {
  final TransactionModel transaction;

  const SplitTransactionScreen({
    super.key,
    required this.transaction,
  });

  @override
  ConsumerState<SplitTransactionScreen> createState() =>
      _SplitTransactionScreenState();
}

class _SplitTransactionScreenState extends ConsumerState<SplitTransactionScreen> {
  final List<SplitPartState> _parts = [];
  bool _isSaving = false;

  @override
  void initState() {
    super.initState();
    // Initialize with 2 parts, splitting the total amount equally
    final halfAmount = widget.transaction.amount / 2;
    _parts.add(SplitPartState(
      initialAmount: halfAmount,
      categoryId: widget.transaction.categoryId,
      initialNote: widget.transaction.note,
    ));
    _parts.add(SplitPartState(
      initialAmount: halfAmount,
      categoryId: null,
    ));
  }

  @override
  void dispose() {
    for (var part in _parts) {
      part.dispose();
    }
    super.dispose();
  }

  double _getSumOfParts() {
    double sum = 0.0;
    for (var part in _parts) {
      final val = double.tryParse(part.amountController.text) ?? 0.0;
      sum += val;
    }
    return sum;
  }

  void _addPart() {
    setState(() {
      _parts.add(SplitPartState(
        initialAmount: 0.0,
        categoryId: null,
      ));
    });
  }

  void _removePart(int index) {
    if (_parts.length <= 2) return;
    setState(() {
      final removed = _parts.removeAt(index);
      removed.dispose();
    });
  }

  Future<void> _performSplit() async {
    final l10n = AppLocalizations.of(context)!;
    final totalSum = _getSumOfParts();
    
    // Safety check
    if ((totalSum - widget.transaction.amount).abs() > 0.01) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(l10n.splitValidationError)),
      );
      return;
    }

    for (var part in _parts) {
      if (part.categoryId == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(l10n.selectCategoryError)),
        );
        return;
      }
    }

    setState(() => _isSaving = true);

    try {
      final notifier = ref.read(transactionProvider.notifier);

      // Part 1: Update original transaction
      final part1 = _parts[0];
      final part1Amount = double.parse(part1.amountController.text);
      final updatedTx = widget.transaction.copyWith(
        amount: part1Amount,
        categoryId: part1.categoryId,
        note: part1.noteController.text,
      );
      await notifier.update(updatedTx);

      // Part 2..N: Add as new transactions
      for (int i = 1; i < _parts.length; i++) {
        final part = _parts[i];
        final partAmount = double.parse(part.amountController.text);
        final newTx = TransactionModel(
          id: '', // Will be generated by server
          type: widget.transaction.type,
          amount: partAmount,
          categoryId: part.categoryId!,
          date: widget.transaction.date,
          note: part.noteController.text,
          currency: widget.transaction.currency,
          isRecurring: false,
          groupId: widget.transaction.groupId,
          userId: widget.transaction.userId,
        );
        await notifier.add(newTx);
      }

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(l10n.splitSuccess)),
        );
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Ошибка при разделении: $e')),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isSaving = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    final categories = ref.watch(categoryProvider);
    final isDark = Theme.of(context).brightness == Brightness.dark;
    
    final totalSum = _getSumOfParts();
    final originalAmount = widget.transaction.amount;
    final diff = originalAmount - totalSum;
    final isMatched = diff.abs() < 0.01;
    final isOver = diff < -0.01;

    final canSave = isMatched && _parts.every((p) => p.categoryId != null && (double.tryParse(p.amountController.text) ?? 0.0) > 0.0) && !_isSaving;

    return Scaffold(
      appBar: AppBar(
        title: Text(l10n.splitTransaction),
      ),
      body: _isSaving
          ? const Center(child: CircularProgressIndicator())
          : Column(
              children: [
                // Info Banner
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(16),
                  color: isDark ? Colors.grey[900] : Colors.grey[100],
                  child: Column(
                    children: [
                      Text(
                        'Исходная сумма',
                        style: TextStyle(
                          fontSize: 12,
                          color: isDark ? Colors.white70 : Colors.black54,
                        ),
                      ),
                      const SizedBox(height: 4),
                      Text(
                        DebtUtils.formatAmount(originalAmount, widget.transaction.currency),
                        style: const TextStyle(
                          fontSize: 24,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      if (widget.transaction.note.isNotEmpty) ...[
                        const SizedBox(height: 4),
                        Text(
                          widget.transaction.note,
                          style: const TextStyle(
                            fontSize: 14,
                            fontStyle: FontStyle.italic,
                            color: Colors.grey,
                          ),
                        ),
                      ],
                    ],
                  ),
                ),
                Expanded(
                  child: ListView.builder(
                    padding: const EdgeInsets.all(16),
                    itemCount: _parts.length,
                    itemBuilder: (context, index) {
                      final part = _parts[index];
                      final partCategory = categories
                          .where((c) => c.id == part.categoryId)
                          .firstOrNull;

                      return Card(
                        margin: const EdgeInsets.only(bottom: 16),
                        elevation: 0,
                        color: isDark ? Colors.grey[900]!.withOpacity(0.5) : Colors.grey[200]!.withOpacity(0.5),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(16),
                          side: BorderSide(
                            color: isDark ? Colors.white12 : Colors.black12,
                          ),
                        ),
                        child: Padding(
                          padding: const EdgeInsets.all(16),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: [
                                  Text(
                                    l10n.splitPartTitle(index + 1),
                                    style: const TextStyle(
                                      fontWeight: FontWeight.bold,
                                      fontSize: 16,
                                    ),
                                  ),
                                  if (_parts.length > 2)
                                    IconButton(
                                      icon: const Icon(Icons.delete_outline, color: Colors.redAccent),
                                      onPressed: () => _removePart(index),
                                    ),
                                ],
                              ),
                              const SizedBox(height: 12),
                              // Amount Field
                              TextField(
                                controller: part.amountController,
                                decoration: InputDecoration(
                                  labelText: l10n.amount,
                                  suffixText: widget.transaction.currency,
                                ),
                                keyboardType: const TextInputType.numberWithOptions(decimal: true),
                                onChanged: (val) {
                                  setState(() {});
                                },
                              ),
                              const SizedBox(height: 12),
                              // Category Selector
                              ListTile(
                                contentPadding: EdgeInsets.zero,
                                title: Text(l10n.category),
                                subtitle: Text(
                                  part.categoryId == null
                                      ? l10n.selectCategory
                                      : partCategory?.getLocalizedName(context) ??
                                          l10n.selectCategory,
                                ),
                                leading: Container(
                                  width: 36,
                                  height: 36,
                                  padding: partCategory?.imageUrl != null ? EdgeInsets.zero : const EdgeInsets.all(8),
                                  decoration: BoxDecoration(
                                    color: partCategory == null
                                        ? Colors.grey.withOpacity(0.2)
                                        : (partCategory.imageUrl != null
                                            ? null
                                            : Color(partCategory.colorValue).withOpacity(0.2)),
                                    shape: BoxShape.circle,
                                    image: partCategory?.imageUrl != null
                                        ? DecorationImage(
                                            image: NetworkImage(partCategory!.imageUrl!),
                                            fit: BoxFit.cover,
                                          )
                                        : null,
                                  ),
                                  child: partCategory?.imageUrl != null
                                      ? null
                                      : Icon(
                                          partCategory == null
                                              ? Icons.category
                                              : IconData(
                                                  partCategory.iconCode,
                                                  fontFamily: 'MaterialIcons',
                                                ),
                                          color: partCategory == null
                                              ? Colors.grey
                                              : Color(partCategory.colorValue),
                                        ),
                                ),
                                trailing: const Icon(Icons.chevron_right),
                                onTap: () {
                                  showModalBottomSheet(
                                    context: context,
                                    isScrollControlled: true,
                                    backgroundColor: Colors.transparent,
                                    builder: (context) => CategoryQuickSelector(
                                      currentCategoryId: part.categoryId ?? '',
                                      onCategorySelected: (id) {
                                        setState(() => part.categoryId = id);
                                      },
                                    ),
                                  );
                                },
                              ),
                              const SizedBox(height: 12),
                              // Note Field
                              TextField(
                                controller: part.noteController,
                                decoration: InputDecoration(
                                  labelText: l10n.note,
                                  hintText: 'Комментарий к этой части',
                                ),
                              ),
                            ],
                          ),
                        ),
                      );
                    },
                  ),
                ),
                // Footer
                SafeArea(
                  child: Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: isDark ? Colors.black : Colors.white,
                      border: Border(
                        top: BorderSide(
                          color: isDark ? Colors.white10 : Colors.black12,
                        ),
                      ),
                    ),
                    child: Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        // Distribution status
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            const Text(
                              'Распределено:',
                              style: TextStyle(fontWeight: FontWeight.w600),
                            ),
                            Text(
                              '${DebtUtils.formatAmount(totalSum, widget.transaction.currency)} / ${DebtUtils.formatAmount(originalAmount, widget.transaction.currency)}',
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                                color: isMatched ? Colors.green : Colors.orange,
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 8),
                        if (!isMatched)
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Text(
                                isOver ? 'Перебор:' : l10n.splitRemaining(''),
                                style: TextStyle(
                                  fontSize: 13,
                                  color: isOver ? Colors.redAccent : Colors.orange,
                                ),
                              ),
                              Text(
                                DebtUtils.formatAmount(diff.abs(), widget.transaction.currency),
                                style: TextStyle(
                                  fontSize: 13,
                                  fontWeight: FontWeight.bold,
                                  color: isOver ? Colors.redAccent : Colors.orange,
                                ),
                              ),
                            ],
                          ),
                        const SizedBox(height: 16),
                        Row(
                          children: [
                            Expanded(
                              child: OutlinedButton.icon(
                                icon: const Icon(Icons.add),
                                label: Text(l10n.addSplitPart),
                                onPressed: _addPart,
                              ),
                            ),
                            const SizedBox(width: 12),
                            Expanded(
                              child: ElevatedButton(
                                onPressed: canSave ? _performSplit : null,
                                style: ElevatedButton.styleFrom(
                                  backgroundColor: Colors.teal[600],
                                  foregroundColor: Colors.white,
                                ),
                                child: const Text('Разделить'),
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
    );
  }
}
